#!/bin/sh

: "
This is a nontrivial example of tracing.
From a podcast, I found an instance of the alpine library (though renamed).
I saw, with happiness, that this is the only js file the page used.
(Some of them use dozens.)
I browsed the page, with dimin, with trace, and made a snapshot.
I renamed the js file and put it on edbrowse.org.
(These trace tests have to run on a website.)
I then made moderate edits to the html, to access the traced js file
instead of the original js file.
We have to vector through a third file in order to defer the script,
as the original was deferred.
You can see the layout in the head section of alpine-start.html,
and also the show paragraph just after <body>.

At this point it is ready to trace, under chrome or edbrowse.
For chrome,  invoke <chromeline on this line

http://www.edbrowse.org/fm/alpine-start.html

For edbrowse, type g on that line.
Either way you get <session text> at the top of the browsed page.

ib2
e2
w trace.out

And there it is, 22723 lines of output.
They are identical from both browsers.
Thus this is a repeatable test.
But it's not a panacea; the page still doesn't render perfectly.
But it's still impressive.

This shell script is an automated way to run the test.
I don't call chrome again; that should not change.
Unless you upgrade chrome or get a more recent snapshot of the js library etc.
This is the same philosophy as the other tests in this directory -
I only run the edbrowse side of things.
This is not included in the runtests script.
It's a bit different, and understanding the
discrepancies, if any, is much more involved.
Example: on the first run I got lots of differences,
but they were in a sort function -
array.sort(compare) where compare is a function that had trace points injected.
Different browsers will implement quicksort in different ways, and that
hardly matters to us.
So I removed those two trace points and ran it again.
Then it came out identical.
So you have to do some analysis, and remove some trace points that give
no information, and (perhaps) add some alerts that give some needed information.
I have indeed added alerts to the traced js file.
"

cd "$(dirname "$0")"
program=../src/edbrowse
$program -c /dev/null <<!
b http://www.edbrowse.org/fm/alpine-start.html
1X
ib2
e2
w trace-alpine-edbrowse
qt
!

if cmp trace-alpine-chrome trace-alpine-edbrowse
then
echo ok
rm trace-alpine-edbrowse
exit 0
fi

#  cmp already printed the message.
exit 1
