#!/bin/sh

# ask crome whether a class and attribute has spillup and spilldown.
# Not a perfect test; some attributes only accept a discrete set of values.
# Perhaps a third optional argument for value; meantime I use nonsense strings.
# You will need your config file and the chrome plugin for this to work.

if [ $# != 2 ]
then
echo "usage spilldowncheck nodeName attribute"
exit 1
fi

node="$1"
attr="$2"

# anything we send to chrome has to end in .html
file=spilltest.html
cat <<! >$file
<head></head><body>
<p id=show></p>
<script>
try {
show = document.getElementById("show");
msg="";
s = document.createElement("$node");
msg += ':' + s["$attr"] + ':' + s.getAttribute("$attr");
s["$attr"] = "abc";
msg += ':' + s["$attr"] + ':' + s.getAttribute("$attr");
s.setAttribute("$attr", "xyz");
msg += ':' + s["$attr"] + ':' + s.getAttribute("$attr");
show.innerHTML = msg;
} catch(e) { show.innerHTML = "blowup " + e; }
</script></body>
!

edbrowse $file <<!
<chromethis
1
qt
!

rm $file
