#!/bin/sh

# A version of spilldowncheck for boolean attributes.

keep=n
if [ $# != 0 -a "$1" = -k ]
then
keep=y
shift
fi

if [ $# != 2 ]
then
echo "usage spilldownboolcheck [-k] nodeName attribute"
exit 1
fi

node="$1"
attr="$2"

file=spilltest.html
cat <<! >$file
<head></head><body>
<p id=show></p>
<script>
try {
show = document.getElementById("show");
msg="";
s = document.createElement("$node");
msg += ':' + s["$attr"] + ':' + s.getAttribute("$attr");
s["$attr"] = "abc";
msg += '@' + s["$attr"] + ':' + s.getAttribute("$attr");
s["$attr"] = false;
msg += ':' + s["$attr"] + ':' + s.getAttribute("$attr");
s["$attr"] = true;
msg += ':' + s["$attr"] + ':' + s.getAttribute("$attr");
s.setAttribute("$attr", "xyz");
msg += '@' + s["$attr"] + ':' + s.getAttribute("$attr");
s.setAttribute("$attr", false);
msg += ':' + s["$attr"] + ':' + s.getAttribute("$attr");
s.setAttribute("$attr", true);
msg += ':' + s["$attr"] + ':' + s.getAttribute("$attr");
s.removeAttribute("$attr");
msg += '@' + s["$attr"] + ':' + s.getAttribute("$attr");
show.innerHTML = msg;
} catch(e) { show.innerHTML = "blowup " + e; }
</script></body>
!

edbrowse $file <<!
<chromethis
1
qt
!

if [ $keep = n ]
then
rm $file
fi
